"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import ClientAvatarV23 from "@/components/media/ClientAvatarV23";

type Props = {
  showToast: (text: string) => void;
  initialClientId?: number | null;
  onOpenBike?: (bikeId: number) => void;
};
type Tab = "overview" | "rentals" | "finance" | "media" | "requests";

function initData(){ return typeof window === "undefined" ? "" : (window as any).Telegram?.WebApp?.initData || ""; }
async function api<T>(url:string,options:RequestInit={}):Promise<T>{const r=await fetch(url,{...options,headers:{"Content-Type":"application/json","x-telegram-init-data":initData(),...(options.headers||{})}});const j=await r.json().catch(()=>({ok:false,error:`HTTP ${r.status}`}));if(!r.ok||!j.ok)throw new Error(typeof j.error==="string"?j.error:j.error?.message||"API error");return j.data as T}
function money(v:unknown){return `${Math.round(Number(v||0)).toLocaleString("ru-RU")} Kč`}
function date(v:unknown){if(!v)return"—";const d=new Date(String(v));return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString("ru-RU")}
function dt(v:unknown){if(!v)return"—";const d=new Date(String(v));return Number.isNaN(d.getTime())?String(v):d.toLocaleString("ru-RU")}
function arr(v:any){return Array.isArray(v)?v:[]}

async function makeAvatarThumbnail(file: File): Promise<File | null> {
  if (!file.type.startsWith("image/")) return null;
  try {
    const bitmap = await createImageBitmap(file);
    const side = Math.min(bitmap.width, bitmap.height);
    const sx = Math.floor((bitmap.width - side) / 2), sy = Math.floor((bitmap.height - side) / 2);
    const canvas = document.createElement("canvas"); canvas.width = 256; canvas.height = 256;
    const ctx = canvas.getContext("2d"); if (!ctx) return null;
    ctx.drawImage(bitmap, sx, sy, side, side, 0, 0, 256, 256); bitmap.close();
    const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, "image/webp", .82));
    if (!blob) return null;
    return new File([blob], "avatar_thumb.webp", { type: "image/webp" });
  } catch { return null; }
}

export default function ClientCenterV23({showToast,initialClientId,onOpenBike}:Props){
  const [rows,setRows]=useState<any[]>([]);const [kpi,setKpi]=useState<any>({});const [q,setQ]=useState("");const [state,setState]=useState("all");
  const [selected,setSelected]=useState<number|null>(initialClientId||null);const [detail,setDetail]=useState<any>(null);const [tab,setTab]=useState<Tab>("overview");const [loading,setLoading]=useState(false);
  const [drive,setDrive]=useState<any>(null);const [mediaType,setMediaType]=useState("avatar");const fileRef=useRef<HTMLInputElement|null>(null);
  const [showCreate,setShowCreate]=useState(false);const [newClient,setNewClient]=useState({name:"",phone:"",email:"",address:"",doc_type:"ID card",doc_number:"",notes:""});

  async function loadList(){setLoading(true);try{const p=new URLSearchParams();if(q.trim())p.set("q",q.trim());if(state!=="all")p.set("state",state);const d=await api<any>(`/api/admin/clients-v23?${p}`);setRows(d.rows||[]);setKpi(d.kpi||{});}catch(e:any){showToast(e.message)}finally{setLoading(false)}}
  async function loadDetail(id:number){setSelected(id);setLoading(true);try{setDetail(await api<any>(`/api/admin/clients-v23/${id}`));}catch(e:any){showToast(e.message)}finally{setLoading(false)}}
  async function refresh(){await loadList();if(selected)await loadDetail(selected)}
  useEffect(()=>{loadList().catch(()=>null);api<any>("/api/admin/client-media/config").then(setDrive).catch(()=>setDrive({configured:false}));},[state]);
  useEffect(()=>{if(initialClientId&&initialClientId!==selected)loadDetail(initialClientId).catch(()=>null)},[initialClientId]);

  async function createClient(){try{if(!newClient.name.trim())return showToast("Укажи имя");const d:any=await api("/api/admin/clients",{method:"POST",body:JSON.stringify(newClient)});showToast("Клиент создан");setShowCreate(false);setNewClient({name:"",phone:"",email:"",address:"",doc_type:"ID card",doc_number:"",notes:""});await loadList();if(d?.id)await loadDetail(Number(d.id));}catch(e:any){showToast(e.message)}}
  async function invite(){if(!selected)return;try{const d:any=await api("/api/admin/invites",{method:"POST",body:JSON.stringify({client_id:selected,notes:"v2.3 client profile"})});try{await navigator.clipboard.writeText(d.link);showToast("Ссылка входа создана и скопирована");}catch{window.prompt("Скопируй ссылку",d.link);}}catch(e:any){showToast(e.message)}}
  async function upload(file:File){if(!selected)return;try{if(!drive?.configured)return showToast("Google Drive ещё не настроен на сервере");setLoading(true);const form=new FormData();form.set("client_id",String(selected));form.set("media_type",mediaType);form.set("file",file);form.set("is_sensitive",["document","contract"].includes(mediaType)?"1":"0");if(mediaType==="avatar"){const thumb=await makeAvatarThumbnail(file);if(thumb)form.set("thumbnail",thumb)}const r=await fetch("/api/admin/client-media",{method:"POST",headers:{"x-telegram-init-data":initData()},body:form});const j=await r.json().catch(()=>({ok:false,error:`HTTP ${r.status}`}));if(!r.ok||!j.ok)throw new Error(typeof j.error==="string"?j.error:j.error?.message||"Upload error");showToast(mediaType==="avatar"?"Фото клиента сохранено":"Файл сохранён");await refresh();}catch(e:any){showToast(e.message)}finally{setLoading(false);if(fileRef.current)fileRef.current.value=""}}
  async function removeMedia(id:number){if(!confirm("Удалить этот файл из профиля?"))return;try{await api(`/api/admin/client-media/${id}`,{method:"DELETE"});showToast("Файл удалён");await refresh()}catch(e:any){showToast(e.message)}}

  const p=detail?.profile;
  const openDebt=useMemo(()=>arr(detail?.open_charges).reduce((s:number,c:any)=>s+Number(c.effective_debt_left||0),0),[detail]);
  return <div className="v23-clients-root">
    <div className="card wide">
      <div className="space"><div><h2 style={{marginBottom:2}}>👥 Client Center · v2.3</h2><div className="small muted">Профиль клиента, его собственные долги, аренды, пересадки, платежи, заявки и приватные файлы.</div></div><div className="row"><button className="btn primary" onClick={()=>setShowCreate(!showCreate)}>+ Клиент</button><button className="btn" onClick={refresh} disabled={loading}>↻</button></div></div>
      <div className="v23-client-kpis"><button className={state==="all"?"active":""} onClick={()=>setState("all")}><span>Всего</span><b>{kpi.total||0}</b></button><button className={state==="active"?"active":""} onClick={()=>setState("active")}><span>Active аренды</span><b>{kpi.active||0}</b></button><button className={state==="debt"?"active":""} onClick={()=>setState("debt")}><span>С долгом</span><b>{kpi.with_debt||0}</b></button><button className={state==="overdue"?"active":""} onClick={()=>setState("overdue")}><span>Просрочка</span><b>{kpi.overdue||0}</b></button><div><span>Долг клиентов</span><b>{money(kpi.total_debt)}</b></div></div>
      <div className="row" style={{marginTop:12}}><input className="input" style={{flex:1,minWidth:240}} value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&loadList()} placeholder="имя / телефон / документ / client # / bike #"/><button className="btn primary" onClick={loadList}>Найти</button></div>
      {showCreate&&<div className="item" style={{marginTop:12}}><h3>Новый клиент</h3><div className="formgrid"><label>Имя<input className="input" value={newClient.name} onChange={e=>setNewClient(x=>({...x,name:e.target.value}))}/></label><label>Телефон<input className="input" value={newClient.phone} onChange={e=>setNewClient(x=>({...x,phone:e.target.value}))}/></label><label>Email<input className="input" value={newClient.email} onChange={e=>setNewClient(x=>({...x,email:e.target.value}))}/></label><label>Адрес<input className="input" value={newClient.address} onChange={e=>setNewClient(x=>({...x,address:e.target.value}))}/></label><label>Документ<select className="select" value={newClient.doc_type} onChange={e=>setNewClient(x=>({...x,doc_type:e.target.value}))}><option value="ID card">ID card</option><option value="passport">passport</option><option value="driver_license">driver license</option><option value="visa">visa / pobyt</option><option value="other">other</option></select></label><label>№ документа<input className="input" value={newClient.doc_number} onChange={e=>setNewClient(x=>({...x,doc_number:e.target.value}))}/></label></div><label>Комментарий<textarea className="textarea" value={newClient.notes} onChange={e=>setNewClient(x=>({...x,notes:e.target.value}))}/></label><button className="btn primary" onClick={createClient}>Создать</button></div>}
    </div>

    <div className="v23-client-master">
      <div className="card v23-client-list"><div className="space"><h3>Клиенты</h3><span className="pill">{rows.length}</span></div><div className="list">{rows.map((r:any)=><button className={`item v23-client-row ${selected===r.client_id?"active":""}`} key={r.client_id} onClick={()=>{setTab("overview");loadDetail(Number(r.client_id))}}><div className="v23-client-list-head"><ClientAvatarV23 mediaId={r.avatar_media_id} name={r.name} size={42}/><div style={{flex:1,minWidth:0}}><div className="space"><b>{r.name||`client #${r.client_id}`}</b><span className="pill">#{r.client_id}</span></div><div className="small muted">{r.phone||"без телефона"} · 🚲 {arr(r.active_bike_ids).map((x:any)=>`#${x}`).join(", ")||"—"}</div></div></div><div className="space" style={{marginTop:6}}><span className="small">active: {r.active_rental_count||0}</span><b className={Number(r.open_debt_total)>0?"dangerText":"okText"}>{money(r.open_debt_total)}</b></div></button>)}{!rows.length&&<p className="muted">Ничего не найдено.</p>}</div></div>

      <div className="v23-client-detail">
        {!selected&&<div className="card"><h3>Выбери клиента</h3></div>}
        {selected&&detail&&p&&<>
          <div className="card"><div className="v23-profile-head"><ClientAvatarV23 mediaId={p.avatar_media_id} name={p.name} size={82} thumb={false}/><div style={{flex:1}}><div className="space"><div><h2 style={{marginBottom:2}}>{p.name}</h2><div className="small muted">client #{p.client_id} · TG {p.telegram_id||"не привязан"}</div></div><button className="btn" onClick={invite}>🔑 Ссылка входа</button></div><div className="small">📞 {p.phone||"—"} · 📧 {p.email||"—"}</div><div className="small muted">🏠 {p.address||"—"}</div></div></div><div className="v23-profile-tabs">{([['overview','Обзор'],['rentals','Аренды'],['finance','Финансы'],['media','Фото / файлы'],['requests','Заявки']] as const).map(([v,l])=><button key={v} className={`btn ${tab===v?"primary":""}`} onClick={()=>setTab(v)}>{l}</button>)}</div></div>

          {tab==="overview"&&<><div className="card"><h3>Сводка клиента</h3><div className="v23-summary-kpis"><div><span>Active rental</span><b>{p.active_rental_count||0}</b></div><div><span>Долг всего</span><b className={Number(p.open_debt_total)>0?"dangerText":"okText"}>{money(p.open_debt_total)}</b></div><div><span>Просрочено</span><b className={Number(p.overdue_total)>0?"dangerText":""}>{money(p.overdue_total)}</b></div><div><span>Платежей всего</span><b>{money(p.payments_total)}</b></div></div><div className="notice small" style={{marginTop:10}}>Долг здесь принадлежит <b>клиенту #{p.client_id}</b> и остаётся у него даже после возврата велосипеда. Новый арендатор старый долг не получает.</div></div><div className="card"><h3>Активные велосипеды</h3><div className="row">{arr(p.active_bike_ids).map((id:any)=><button className="btn" key={id} onClick={()=>onOpenBike?.(Number(id))}>🚲 #{id}</button>)}{!arr(p.active_bike_ids).length&&<span className="muted">Нет active аренды.</span>}</div></div><div className="card"><h3>Данные</h3><div className="kv"><div>Телефон</div><div>{p.phone||"—"}</div><div>Email</div><div>{p.email||"—"}</div><div>Адрес</div><div>{p.address||"—"}</div><div>Документ</div><div>{p.doc_type||"—"} · {p.doc_number||"—"}</div><div>Заметка</div><div>{p.notes||"—"}</div></div></div></>}

          {tab==="rentals"&&<><div className="card"><h3>История аренды</h3><div className="list">{(detail.rentals||[]).map((r:any)=><div className="item" key={r.id}><div className="space"><b>Rental #{r.id} · bike #{r.bike_id}</b><span className={`pill ${r.status==="active"?"ok":""}`}>{r.status}</span></div><div className="small muted">{date(r.start_date)} → {r.end_date?date(r.end_date):"сейчас"} · {money(r.price)}</div><button className="btn" style={{marginTop:7}} onClick={()=>onOpenBike?.(Number(r.bike_id))}>Открыть bike #{r.bike_id}</button></div>)}</div></div><div className="card"><h3>Пересадки / assignments</h3><div className="list">{(detail.assignment_history||[]).map((a:any)=><div className="item" key={a.id}><div className="space"><b>🚲 #{a.bike_id} · rental #{a.rental_id}</b><span className={`pill ${a.ended_at?"":"ok"}`}>{a.ended_at?"ended":"current"}</span></div><div className="small muted">{dt(a.started_at)} → {a.ended_at?dt(a.ended_at):"сейчас"} · {a.source}</div></div>)}{!(detail.assignment_history||[]).length&&<p className="muted">Нет history.</p>}</div></div></>}

          {tab==="finance"&&<><div className="card"><h3>Финансы клиента</h3><div className="v23-summary-kpis"><div><span>Начислено</span><b>{money(p.charged_total)}</b></div><div><span>Распределено по начислениям</span><b>{money(p.effective_paid_total)}</b></div><div><span>Payments</span><b>{money(p.payments_total)}</b></div><div><span>Открыто</span><b className={openDebt>0?"dangerText":"okText"}>{money(openDebt)}</b></div></div></div><div className="card"><h3>Открытые charges</h3><div className="list">{arr(detail.open_charges).map((c:any)=><div className="item" key={c.id}><div className="space"><b>#{c.id} {c.charge_type}</b><span className="dangerText">{money(c.effective_debt_left)}</span></div><div className="small muted">rental #{c.rental_id||"—"} · bike #{c.bike_id||"—"} · до {date(c.due_date)}</div></div>)}{!arr(detail.open_charges).length&&<p className="okText">Открытых долгов нет.</p>}</div></div><div className="card"><h3>Последние платежи</h3><div className="list">{(detail.payments||[]).slice(0,100).map((x:any)=><div className="item" key={x.id}><div className="space"><b>#{x.id} · {date(x.payment_date)}</b><span>{money(x.amount)}</span></div><div className="small muted">rental #{x.rental_id||"—"} · {x.method} · {x.notes||""}</div></div>)}</div></div></>}

          {tab==="media"&&<><div className="card"><div className="space"><div><h3>Фото / файлы клиента</h3><div className="small muted">Оригиналы и thumbnails — приватно в Google Drive. В Postgres только file_id + metadata.</div></div><span className={`pill ${drive?.configured?"ok":"warn"}`}>{drive?.configured?"Drive OK":"Drive не настроен"}</span></div><div className="row" style={{marginTop:10}}><select className="select" style={{maxWidth:190}} value={mediaType} onChange={e=>setMediaType(e.target.value)}><option value="avatar">Фото клиента</option><option value="document">Документ</option><option value="contract">Контракт / файл</option><option value="other">Другое</option></select><input ref={fileRef} className="input" type="file" accept={mediaType==="avatar"?"image/*":"*/*"} onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}} disabled={!drive?.configured||loading}/></div>{!drive?.configured&&<div className="notice small" style={{marginTop:8}}>UI и БД уже готовы. Для личного Google Drive добавь OAuth env: GOOGLE_DRIVE_CLIENT_ID, GOOGLE_DRIVE_CLIENT_SECRET, GOOGLE_DRIVE_REFRESH_TOKEN и GOOGLE_DRIVE_CLIENT_MEDIA_FOLDER_ID (см. ENV_V23.example.txt).</div>}</div><div className="card"><div className="list">{arr(detail.media).map((m:any)=><div className="item" key={m.id}><div className="space"><div className="row">{m.media_type==="avatar"&&<ClientAvatarV23 mediaId={m.id} name={p.name} size={46}/>}<div><b>{m.file_name||`${m.media_type} #${m.id}`}</b><div className="small muted">{m.media_type} · {m.mime_type||"—"} · {m.size_bytes?`${Math.round(m.size_bytes/1024)} KB`:"—"}</div></div></div><button className="btn danger" onClick={()=>removeMedia(Number(m.id))}>Удалить</button></div><div className="small muted">{date(m.created_at)} · {m.is_sensitive?"🔒 sensitive":"private"} {m.is_current?"· current":""}</div></div>)}{!arr(detail.media).length&&<p className="muted">Файлов пока нет.</p>}</div></div></>}

          {tab==="requests"&&<div className="card"><h3>Заявки клиента</h3><div className="list">{arr(detail.requests).map((r:any)=><div className="item" key={r.id}><div className="space"><b>#{r.id} {r.title||r.request_type}</b><span className="pill">{r.status}</span></div><div className="small muted">{dt(r.created_at)} · {r.priority||"normal"} · bike #{r.bike_id||"—"}</div>{r.description&&<div>{r.description}</div>}{r.admin_note&&<div className="small muted">Админ: {r.admin_note}</div>}</div>)}{!arr(detail.requests).length&&<p className="muted">Заявок нет.</p>}</div></div>}
        </>}
      </div>
    </div>
    <style>{`
      .v23-clients-root{display:grid;gap:12px}.v23-client-kpis{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px;margin-top:12px}.v23-client-kpis>button,.v23-client-kpis>div{border:1px solid rgba(100,200,140,.16);background:rgba(5,30,20,.45);border-radius:13px;padding:10px;text-align:left;color:inherit;display:flex;flex-direction:column}.v23-client-kpis button.active{box-shadow:inset 0 0 0 1px rgba(60,220,120,.45)}.v23-client-kpis span{font-size:12px;opacity:.7}.v23-client-kpis b{font-size:20px}.v23-client-master{display:grid;grid-template-columns:minmax(310px,.78fr) minmax(0,1.55fr);gap:12px;align-items:start}.v23-client-list{position:sticky;top:8px;max-height:calc(100vh - 20px);overflow:auto}.v23-client-row{text-align:left;width:100%}.v23-client-list-head{display:flex;align-items:center;gap:9px}.v23-profile-head{display:flex;align-items:center;gap:14px}.v23-profile-tabs{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.v23-summary-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.v23-summary-kpis>div{border:1px solid rgba(255,255,255,.08);border-radius:12px;padding:10px;display:flex;flex-direction:column}.v23-summary-kpis span{font-size:12px;opacity:.7}.v23-summary-kpis b{font-size:18px}@media(max-width:950px){.v23-client-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}.v23-client-master{grid-template-columns:1fr}.v23-client-list{position:static;max-height:none}.v23-summary-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}}
    `}</style>
  </div>
}
